services:
  - type: web
    name: photo-to-text-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    packages:
      - tesseract-ocr
      - libtesseract-dev